# Generated by Django 4.0.4 on 2022-06-01 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0003_customerdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customerDetails',
            new_name='customerDetail',
        ),
    ]
