# Generated by Django 4.0.4 on 2022-06-01 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0004_rename_customerdetails_customerdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySite.customerdetail')),
            ],
        ),
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySite.bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySite.product')),
            ],
        ),
    ]
