# Generated by Django 4.0.4 on 2022-06-01 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0006_rename_bid_bill_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartProducts',
            new_name='CartItems',
        ),
    ]
