# Generated by Django 4.0.4 on 2022-06-01 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0007_rename_cartproducts_cartitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
    ]
